# -*- coding: utf-8 -*

TOPICS = [
    {"id": "01_01", "topic": "Hierarchical Network Design and Why Layers Exist", "slug": "hierarchical_network_design_and_why_laye"},
    {"id": "01_02", "topic": "The Access Layer: Role and Design Requirements", "slug": "the_access_layer_role_and_design_require"},
    {"id": "01_03", "topic": "The Distribution Layer: Role and Design Requirements", "slug": "the_distribution_layer_role_and_design_r"},
    {"id": "01_04", "topic": "The Core Layer and When a Network Needs One", "slug": "the_core_layer_and_when_a_network_needs_"},
    {"id": "01_05", "topic": "Two-Tier Collapsed Core Design", "slug": "twotier_collapsed_core_design"},
    {"id": "01_06", "topic": "Three-Tier Design and What Justifies the Extra Layer", "slug": "threetier_design_and_what_justifies_the_"},
    {"id": "01_07", "topic": "Spine-Leaf Fabric Design", "slug": "spineleaf_fabric_design"},
    {"id": "01_08", "topic": "Cisco Enterprise Architecture Model and Network Modules", "slug": "cisco_enterprise_architecture_model_and_"},
    {"id": "01_09", "topic": "Layer 2 Access Design and Its Dependence on STP", "slug": "layer_2_access_design_and_its_dependence"},
    {"id": "01_10", "topic": "Routed Access Design: Moving Layer 3 to the Edge", "slug": "routed_access_design_moving_layer_3_to_t"},
    {"id": "01_11", "topic": "Comparing Layer 2 Access and Routed Access Trade-offs", "slug": "comparing_layer_2_access_and_routed_acce"},
    {"id": "01_12", "topic": "Switch Stacking with StackWise", "slug": "switch_stacking_with_stackwise"},
    {"id": "01_13", "topic": "VSS and StackWise Virtual", "slug": "vss_and_stackwise_virtual"},
    {"id": "01_14", "topic": "Multichassis EtherChannel in Campus Design", "slug": "multichassis_etherchannel_in_campus_desi"},
    {"id": "01_15", "topic": "High Availability: Stateful Switchover (SSO)", "slug": "high_availability_stateful_switchover_ss"},
    {"id": "01_16", "topic": "High Availability: Nonstop Forwarding and Graceful Restart", "slug": "high_availability_nonstop_forwarding_and"},
    {"id": "01_17", "topic": "On-Premises versus Cloud Deployment Models", "slug": "onpremises_versus_cloud_deployment_model"},
    {"id": "01_18", "topic": "Cloud Service Models: IaaS, PaaS and SaaS", "slug": "cloud_service_models_iaas_paas_and_saas"},
    {"id": "02_01", "topic": "Control Plane, Data Plane and Management Plane", "slug": "control_plane_data_plane_and_management_"},
    {"id": "02_02", "topic": "Process Switching and Why It Is Slow", "slug": "process_switching_and_why_it_is_slow"},
    {"id": "02_03", "topic": "Fast Switching and the Route Cache", "slug": "fast_switching_and_the_route_cache"},
    {"id": "02_04", "topic": "Cisco Express Forwarding: The Forwarding Model", "slug": "cisco_express_forwarding_the_forwarding_"},
    {"id": "02_05", "topic": "The CEF Forwarding Information Base", "slug": "the_cef_forwarding_information_base"},
    {"id": "02_06", "topic": "The CEF Adjacency Table", "slug": "the_cef_adjacency_table"},
    {"id": "02_07", "topic": "TCAM: How Ternary Matching Works in Hardware", "slug": "tcam_how_ternary_matching_works_in_hardw"},
    {"id": "02_08", "topic": "TCAM Allocation and SDM Templates", "slug": "tcam_allocation_and_sdm_templates"},
    {"id": "02_09", "topic": "Exception Punting: When Traffic Reaches the CPU", "slug": "exception_punting_when_traffic_reaches_t"},
    {"id": "02_10", "topic": "Diagnosing Hardware Forwarding and Performance Limits", "slug": "diagnosing_hardware_forwarding_and_perfo"},
    {"id": "03_01", "topic": "VLAN Fundamentals and Broadcast Domain Design", "slug": "vlan_fundamentals_and_broadcast_domain_d"},
    {"id": "03_02", "topic": "Configuring VLANs and Access Ports", "slug": "configuring_vlans_and_access_ports"},
    {"id": "03_03", "topic": "802.1Q Trunk Encapsulation and Frame Tagging", "slug": "8021q_trunk_encapsulation_and_frame_tagg"},
    {"id": "03_04", "topic": "Native VLAN Behaviour and Mismatch Risks", "slug": "native_vlan_behaviour_and_mismatch_risks"},
    {"id": "03_05", "topic": "Dynamic Trunking Protocol and Trunk Negotiation", "slug": "dynamic_trunking_protocol_and_trunk_nego"},
    {"id": "03_06", "topic": "VTP Modes, Versions and Revision Number Risks", "slug": "vtp_modes_versions_and_revision_number_r"},
    {"id": "03_07", "topic": "Inter-VLAN Routing with Switched Virtual Interfaces", "slug": "intervlan_routing_with_switched_virtual_"},
    {"id": "03_08", "topic": "Routed Ports on Layer 3 Switches", "slug": "routed_ports_on_layer_3_switches"},
    {"id": "03_09", "topic": "Troubleshooting VLAN and Trunk Connectivity", "slug": "troubleshooting_vlan_and_trunk_connectiv"},
    {"id": "04_01", "topic": "Layer 2 Loops and the Problem Spanning Tree Solves", "slug": "layer_2_loops_and_the_problem_spanning_t"},
    {"id": "04_02", "topic": "The Bridge ID and Root Bridge Election", "slug": "the_bridge_id_and_root_bridge_election"},
    {"id": "04_03", "topic": "Root Port Selection and Path Cost", "slug": "root_port_selection_and_path_cost"},
    {"id": "04_04", "topic": "Designated Port Selection", "slug": "designated_port_selection"},
    {"id": "04_05", "topic": "Classic STP Port States and Timers", "slug": "classic_stp_port_states_and_timers"},
    {"id": "04_06", "topic": "RSTP Port Roles and Port States", "slug": "rstp_port_roles_and_port_states"},
    {"id": "04_07", "topic": "The RSTP Proposal and Agreement Handshake", "slug": "the_rstp_proposal_and_agreement_handshak"},
    {"id": "04_08", "topic": "RSTP Topology Change Handling", "slug": "rstp_topology_change_handling"},
    {"id": "04_09", "topic": "MSTP Instances and Region Configuration", "slug": "mstp_instances_and_region_configuration"},
    {"id": "04_10", "topic": "MSTP Boundary Behaviour with RSTP and PVST+", "slug": "mstp_boundary_behaviour_with_rstp_and_pv"},
    {"id": "04_11", "topic": "PortFast and Edge Ports", "slug": "portfast_and_edge_ports"},
    {"id": "04_12", "topic": "BPDU Guard", "slug": "bpdu_guard"},
    {"id": "04_13", "topic": "BPDU Filter", "slug": "bpdu_filter"},
    {"id": "04_14", "topic": "Root Guard", "slug": "root_guard"},
    {"id": "04_15", "topic": "Loop Guard and UDLD", "slug": "loop_guard_and_udld"},
    {"id": "04_16", "topic": "Troubleshooting Spanning Tree Convergence", "slug": "troubleshooting_spanning_tree_convergenc"},
    {"id": "05_01", "topic": "EtherChannel Concepts and Bundling Requirements", "slug": "etherchannel_concepts_and_bundling_requi"},
    {"id": "05_02", "topic": "LACP Negotiation and Modes", "slug": "lacp_negotiation_and_modes"},
    {"id": "05_03", "topic": "PAgP Negotiation and Modes", "slug": "pagp_negotiation_and_modes"},
    {"id": "05_04", "topic": "Static On Mode and the Risks of Skipping Negotiation", "slug": "static_on_mode_and_the_risks_of_skipping"},
    {"id": "05_05", "topic": "EtherChannel Load Balancing Hash Algorithms", "slug": "etherchannel_load_balancing_hash_algorit"},
    {"id": "05_06", "topic": "Traffic Polarization and Hash Tuning", "slug": "traffic_polarization_and_hash_tuning"},
    {"id": "05_07", "topic": "Layer 3 EtherChannel", "slug": "layer_3_etherchannel"},
    {"id": "05_08", "topic": "Troubleshooting EtherChannel Bundling Failures", "slug": "troubleshooting_etherchannel_bundling_fa"},
    {"id": "06_01", "topic": "The Routing Table and Route Selection Order", "slug": "the_routing_table_and_route_selection_or"},
    {"id": "06_02", "topic": "Administrative Distance", "slug": "administrative_distance"},
    {"id": "06_03", "topic": "Longest Prefix Match", "slug": "longest_prefix_match"},
    {"id": "06_04", "topic": "Comparing Routing Protocol Metrics", "slug": "comparing_routing_protocol_metrics"},
    {"id": "06_05", "topic": "Static Routes, Default Routes and Floating Statics", "slug": "static_routes_default_routes_and_floatin"},
    {"id": "06_06", "topic": "Route Redistribution Fundamentals", "slug": "route_redistribution_fundamentals"},
    {"id": "06_07", "topic": "Route Maps: Structure and Processing Logic", "slug": "route_maps_structure_and_processing_logi"},
    {"id": "06_08", "topic": "Prefix Lists for Route Filtering", "slug": "prefix_lists_for_route_filtering"},
    {"id": "06_09", "topic": "Policy-Based Routing", "slug": "policybased_routing"},
    {"id": "06_10", "topic": "VRF-Lite: Separating Routing Tables on One Device", "slug": "vrflite_separating_routing_tables_on_one"},
    {"id": "07_01", "topic": "EIGRP Neighbor Discovery and Adjacency Requirements", "slug": "eigrp_neighbor_discovery_and_adjacency_r"},
    {"id": "07_02", "topic": "EIGRP Metric Components and K-Values", "slug": "eigrp_metric_components_and_kvalues"},
    {"id": "07_03", "topic": "The DUAL Algorithm", "slug": "the_dual_algorithm"},
    {"id": "07_04", "topic": "Feasible Distance, Reported Distance and the Feasibility Condition", "slug": "feasible_distance_reported_distance_and_"},
    {"id": "07_05", "topic": "Successors and Feasible Successors", "slug": "successors_and_feasible_successors"},
    {"id": "07_06", "topic": "The EIGRP Query Process and Stuck-In-Active", "slug": "the_eigrp_query_process_and_stuckinactiv"},
    {"id": "07_07", "topic": "EIGRP Summarization and Stub Routing", "slug": "eigrp_summarization_and_stub_routing"},
    {"id": "07_08", "topic": "Configuring and Verifying EIGRP", "slug": "configuring_and_verifying_eigrp"},
    {"id": "07_09", "topic": "Troubleshooting EIGRP Neighbor and Route Problems", "slug": "troubleshooting_eigrp_neighbor_and_route"},
    {"id": "08_01", "topic": "OSPF Link-State Operation and the Link-State Database", "slug": "ospf_linkstate_operation_and_the_linksta"},
    {"id": "08_02", "topic": "OSPF Router ID Selection", "slug": "ospf_router_id_selection"},
    {"id": "08_03", "topic": "OSPF Areas and Router Roles", "slug": "ospf_areas_and_router_roles"},
    {"id": "08_04", "topic": "OSPF Hello Packets and Neighbor Requirements", "slug": "ospf_hello_packets_and_neighbor_requirem"},
    {"id": "08_05", "topic": "OSPF Neighbor States and Adjacency Formation", "slug": "ospf_neighbor_states_and_adjacency_forma"},
    {"id": "08_06", "topic": "OSPF Network Types", "slug": "ospf_network_types"},
    {"id": "08_07", "topic": "DR and BDR Election on Multi-Access Networks", "slug": "dr_and_bdr_election_on_multiaccess_netwo"},
    {"id": "08_08", "topic": "OSPF Cost and Reference Bandwidth", "slug": "ospf_cost_and_reference_bandwidth"},
    {"id": "08_09", "topic": "LSA Type 1: Router LSA", "slug": "lsa_type_1_router_lsa"},
    {"id": "08_10", "topic": "LSA Type 2: Network LSA", "slug": "lsa_type_2_network_lsa"},
    {"id": "08_11", "topic": "LSA Type 3 and Inter-Area Route Propagation", "slug": "lsa_type_3_and_interarea_route_propagati"},
    {"id": "08_12", "topic": "LSA Type 4 and Type 5: External Routes and the ASBR", "slug": "lsa_type_4_and_type_5_external_routes_an"},
    {"id": "08_13", "topic": "LSA Type 7 and NSSA Translation", "slug": "lsa_type_7_and_nssa_translation"},
    {"id": "08_14", "topic": "Stub and Totally Stubby Areas", "slug": "stub_and_totally_stubby_areas"},
    {"id": "08_15", "topic": "OSPF Summarization at the ABR and ASBR", "slug": "ospf_summarization_at_the_abr_and_asbr"},
    {"id": "08_16", "topic": "SPF Calculation and Throttle Timers", "slug": "spf_calculation_and_throttle_timers"},
    {"id": "08_17", "topic": "OSPFv3 for IPv6", "slug": "ospfv3_for_ipv6"},
    {"id": "08_18", "topic": "Troubleshooting OSPF Adjacency Failures", "slug": "troubleshooting_ospf_adjacency_failures"},
    {"id": "09_01", "topic": "BGP Fundamentals: eBGP versus iBGP", "slug": "bgp_fundamentals_ebgp_versus_ibgp"},
    {"id": "09_02", "topic": "The BGP Finite State Machine", "slug": "the_bgp_finite_state_machine"},
    {"id": "09_03", "topic": "BGP Message Types", "slug": "bgp_message_types"},
    {"id": "09_04", "topic": "BGP Neighbor Establishment and Troubleshooting", "slug": "bgp_neighbor_establishment_and_troublesh"},
    {"id": "09_05", "topic": "Well-Known and Optional Path Attributes", "slug": "wellknown_and_optional_path_attributes"},
    {"id": "09_06", "topic": "Weight and Local Preference", "slug": "weight_and_local_preference"},
    {"id": "09_07", "topic": "AS Path and Origin", "slug": "as_path_and_origin"},
    {"id": "09_08", "topic": "MED and Community Attributes", "slug": "med_and_community_attributes"},
    {"id": "09_09", "topic": "The BGP Best Path Selection Algorithm", "slug": "the_bgp_best_path_selection_algorithm"},
    {"id": "09_10", "topic": "Influencing Inbound and Outbound Path Selection", "slug": "influencing_inbound_and_outbound_path_se"},
    {"id": "09_11", "topic": "Configuring and Verifying eBGP", "slug": "configuring_and_verifying_ebgp"},
    {"id": "10_01", "topic": "First Hop Redundancy Concepts", "slug": "first_hop_redundancy_concepts"},
    {"id": "10_02", "topic": "HSRP Operation, Priority and Preemption", "slug": "hsrp_operation_priority_and_preemption"},
    {"id": "10_03", "topic": "VRRP Operation and How It Differs from HSRP", "slug": "vrrp_operation_and_how_it_differs_from_h"},
    {"id": "10_04", "topic": "GLBP and Active Load Sharing", "slug": "glbp_and_active_load_sharing"},
    {"id": "10_05", "topic": "FHRP Object Tracking", "slug": "fhrp_object_tracking"},
    {"id": "10_06", "topic": "NAT Concepts and Address Terminology", "slug": "nat_concepts_and_address_terminology"},
    {"id": "10_07", "topic": "Static and Dynamic NAT", "slug": "static_and_dynamic_nat"},
    {"id": "10_08", "topic": "PAT and Port Translation", "slug": "pat_and_port_translation"},
    {"id": "10_09", "topic": "Enterprise Internet Edge Design", "slug": "enterprise_internet_edge_design"},
    {"id": "10_10", "topic": "DHCP Server, Client and Relay Operation", "slug": "dhcp_server_client_and_relay_operation"},
    {"id": "11_01", "topic": "GRE Tunnel Operation and Configuration", "slug": "gre_tunnel_operation_and_configuration"},
    {"id": "11_02", "topic": "Tunnel MTU, Fragmentation and MSS Adjustment", "slug": "tunnel_mtu_fragmentation_and_mss_adjustm"},
    {"id": "11_03", "topic": "IPsec Fundamentals: AH and ESP", "slug": "ipsec_fundamentals_ah_and_esp"},
    {"id": "11_04", "topic": "IKE Phases and Diffie-Hellman Groups", "slug": "ike_phases_and_diffiehellman_groups"},
    {"id": "11_05", "topic": "GRE over IPsec", "slug": "gre_over_ipsec"},
    {"id": "11_06", "topic": "Comparing Site-to-Site VPN Technologies", "slug": "comparing_sitetosite_vpn_technologies"},
    {"id": "11_07", "topic": "LISP Architecture and Component Roles", "slug": "lisp_architecture_and_component_roles"},
    {"id": "11_08", "topic": "The LISP Map-Request and Map-Reply Flow", "slug": "the_lisp_maprequest_and_mapreply_flow"},
    {"id": "11_09", "topic": "LISP Map Cache and PxTR Interworking", "slug": "lisp_map_cache_and_pxtr_interworking"},
    {"id": "11_10", "topic": "VXLAN Encapsulation Format and the VNI", "slug": "vxlan_encapsulation_format_and_the_vni"},
    {"id": "11_11", "topic": "VXLAN VTEPs and Data Plane Forwarding", "slug": "vxlan_vteps_and_data_plane_forwarding"},
    {"id": "11_12", "topic": "VXLAN MTU Impact and Anycast Gateway", "slug": "vxlan_mtu_impact_and_anycast_gateway"},
    {"id": "12_01", "topic": "Server Virtualization Fundamentals", "slug": "server_virtualization_fundamentals"},
    {"id": "12_02", "topic": "Type-1 and Type-2 Hypervisors", "slug": "type1_and_type2_hypervisors"},
    {"id": "12_03", "topic": "Virtual Machines and Resource Allocation", "slug": "virtual_machines_and_resource_allocation"},
    {"id": "12_04", "topic": "Virtual Switching and VM Connectivity", "slug": "virtual_switching_and_vm_connectivity"},
    {"id": "12_05", "topic": "Containers versus Virtual Machines", "slug": "containers_versus_virtual_machines"},
    {"id": "12_06", "topic": "Network Functions Virtualization", "slug": "network_functions_virtualization"},
    {"id": "12_07", "topic": "Virtualization Overhead and Hardware Abstraction", "slug": "virtualization_overhead_and_hardware_abs"},
    {"id": "13_01", "topic": "RF Fundamentals and Signal Behaviour", "slug": "rf_fundamentals_and_signal_behaviour"},
    {"id": "13_02", "topic": "802.11 Standards and Modulation", "slug": "80211_standards_and_modulation"},
    {"id": "13_03", "topic": "Channel Planning and Interference Management", "slug": "channel_planning_and_interference_manage"},
    {"id": "13_04", "topic": "Antenna Types and Coverage Patterns", "slug": "antenna_types_and_coverage_patterns"},
    {"id": "13_05", "topic": "Autonomous, Cloud and Split-MAC Architectures", "slug": "autonomous_cloud_and_splitmac_architectu"},
    {"id": "13_06", "topic": "CAPWAP Control and Data Tunnels", "slug": "capwap_control_and_data_tunnels"},
    {"id": "13_07", "topic": "Access Point Modes and Deployment Options", "slug": "access_point_modes_and_deployment_option"},
    {"id": "13_08", "topic": "The AP Join Process and WLC Discovery", "slug": "the_ap_join_process_and_wlc_discovery"},
    {"id": "13_09", "topic": "Intra-Controller Roaming", "slug": "intracontroller_roaming"},
    {"id": "13_10", "topic": "Inter-Controller Layer 2 and Layer 3 Roaming", "slug": "intercontroller_layer_2_and_layer_3_roam"},
    {"id": "13_11", "topic": "Location Services and Client Tracking", "slug": "location_services_and_client_tracking"},
    {"id": "13_12", "topic": "Wireless Client Authentication Methods", "slug": "wireless_client_authentication_methods"},
    {"id": "13_13", "topic": "WPA2 and WPA3 Security", "slug": "wpa2_and_wpa3_security"},
    {"id": "13_14", "topic": "Troubleshooting Wireless Client Connectivity", "slug": "troubleshooting_wireless_client_connecti"},
    {"id": "14_01", "topic": "Multicast Addressing and Layer 2 MAC Mapping", "slug": "multicast_addressing_and_layer_2_mac_map"},
    {"id": "14_02", "topic": "IGMPv2 Operation", "slug": "igmpv2_operation"},
    {"id": "14_03", "topic": "IGMPv3 and Source-Specific Multicast", "slug": "igmpv3_and_sourcespecific_multicast"},
    {"id": "14_04", "topic": "IGMP Snooping", "slug": "igmp_snooping"},
    {"id": "14_05", "topic": "The Reverse Path Forwarding Check", "slug": "the_reverse_path_forwarding_check"},
    {"id": "14_06", "topic": "PIM Dense Mode", "slug": "pim_dense_mode"},
    {"id": "14_07", "topic": "PIM Sparse Mode and the Rendezvous Point", "slug": "pim_sparse_mode_and_the_rendezvous_point"},
    {"id": "14_08", "topic": "The PIM Register Process and SPT Switchover", "slug": "the_pim_register_process_and_spt_switcho"},
    {"id": "14_09", "topic": "PIM Designated Router Election", "slug": "pim_designated_router_election"},
    {"id": "14_10", "topic": "The PIM Assert Mechanism", "slug": "the_pim_assert_mechanism"},
    {"id": "14_11", "topic": "Bidirectional PIM", "slug": "bidirectional_pim"},
    {"id": "14_12", "topic": "MSDP and Inter-Domain Multicast", "slug": "msdp_and_interdomain_multicast"},
    {"id": "14_13", "topic": "RP Discovery: Static, Auto-RP and BSR", "slug": "rp_discovery_static_autorp_and_bsr"},
    {"id": "15_01", "topic": "QoS Requirements: Delay, Jitter and Loss", "slug": "qos_requirements_delay_jitter_and_loss"},
    {"id": "15_02", "topic": "Traffic Classification and NBAR", "slug": "traffic_classification_and_nbar"},
    {"id": "15_03", "topic": "Marking with DSCP, IP Precedence and CoS", "slug": "marking_with_dscp_ip_precedence_and_cos"},
    {"id": "15_04", "topic": "Trust Boundaries", "slug": "trust_boundaries"},
    {"id": "15_05", "topic": "Queuing and Class-Based Weighted Fair Queuing", "slug": "queuing_and_classbased_weighted_fair_que"},
    {"id": "15_06", "topic": "Low Latency Queuing for Voice", "slug": "low_latency_queuing_for_voice"},
    {"id": "15_07", "topic": "Policing and the Token Bucket Algorithm", "slug": "policing_and_the_token_bucket_algorithm"},
    {"id": "15_08", "topic": "Traffic Shaping and Contract Enforcement", "slug": "traffic_shaping_and_contract_enforcement"},
    {"id": "15_09", "topic": "Congestion Avoidance with WRED", "slug": "congestion_avoidance_with_wred"},
    {"id": "15_10", "topic": "QoS Models: IntServ and DiffServ", "slug": "qos_models_intserv_and_diffserv"},
    {"id": "15_11", "topic": "Interpreting an MQC QoS Configuration", "slug": "interpreting_an_mqc_qos_configuration"},
    {"id": "16_01", "topic": "Syslog Severity Levels and Message Structure", "slug": "syslog_severity_levels_and_message_struc"},
    {"id": "16_02", "topic": "SNMP Versions and Security Models", "slug": "snmp_versions_and_security_models"},
    {"id": "16_03", "topic": "NetFlow Concepts and Flow Records", "slug": "netflow_concepts_and_flow_records"},
    {"id": "16_04", "topic": "Flexible NetFlow Configuration", "slug": "flexible_netflow_configuration"},
    {"id": "16_05", "topic": "Model-Driven Telemetry and gRPC", "slug": "modeldriven_telemetry_and_grpc"},
    {"id": "16_06", "topic": "IPFIX and Telemetry Data Formats", "slug": "ipfix_and_telemetry_data_formats"},
    {"id": "16_07", "topic": "NTP Operation and Stratum Hierarchy", "slug": "ntp_operation_and_stratum_hierarchy"},
    {"id": "16_08", "topic": "PTP and Precision Timing", "slug": "ptp_and_precision_timing"},
    {"id": "16_09", "topic": "IP SLA Operations and Thresholds", "slug": "ip_sla_operations_and_thresholds"},
    {"id": "16_10", "topic": "SPAN and RSPAN", "slug": "span_and_rspan"},
    {"id": "16_11", "topic": "ERSPAN", "slug": "erspan"},
    {"id": "16_12", "topic": "EEM Applets and Event Detectors", "slug": "eem_applets_and_event_detectors"},
    {"id": "16_13", "topic": "EEM Actions and AAA Command Authorization Interaction", "slug": "eem_actions_and_aaa_command_authorizatio"},
    {"id": "16_14", "topic": "Debug and Conditional Debug", "slug": "debug_and_conditional_debug"},
    {"id": "16_15", "topic": "Interpreting Ping and Traceroute Output", "slug": "interpreting_ping_and_traceroute_output"},
    {"id": "16_16", "topic": "A Structured Troubleshooting Methodology", "slug": "a_structured_troubleshooting_methodology"},
    {"id": "17_01", "topic": "Standard and Extended Access Control Lists", "slug": "standard_and_extended_access_control_lis"},
    {"id": "17_02", "topic": "Named and Time-Based ACLs", "slug": "named_and_timebased_acls"},
    {"id": "17_03", "topic": "ACL Placement and Troubleshooting", "slug": "acl_placement_and_troubleshooting"},
    {"id": "17_04", "topic": "Control Plane Policing Concepts", "slug": "control_plane_policing_concepts"},
    {"id": "17_05", "topic": "Configuring CoPP Policies", "slug": "configuring_copp_policies"},
    {"id": "17_06", "topic": "Device Access Hardening", "slug": "device_access_hardening"},
    {"id": "17_07", "topic": "Line Configuration and Local User Authentication", "slug": "line_configuration_and_local_user_authen"},
    {"id": "17_08", "topic": "Password Management and Encryption Types", "slug": "password_management_and_encryption_types"},
    {"id": "18_01", "topic": "The AAA Framework: Authentication, Authorization and Accounting", "slug": "the_aaa_framework_authentication_authori"},
    {"id": "18_02", "topic": "RADIUS Operation and Message Flow", "slug": "radius_operation_and_message_flow"},
    {"id": "18_03", "topic": "TACACS+ Operation and How It Differs from RADIUS", "slug": "tacacs_operation_and_how_it_differs_from"},
    {"id": "18_04", "topic": "802.1X Components and the EAP Exchange", "slug": "8021x_components_and_the_eap_exchange"},
    {"id": "18_05", "topic": "Comparing EAP Methods", "slug": "comparing_eap_methods"},
    {"id": "18_06", "topic": "MAC Authentication Bypass", "slug": "mac_authentication_bypass"},
    {"id": "18_07", "topic": "Web Authentication", "slug": "web_authentication"},
    {"id": "18_08", "topic": "RADIUS Change of Authorization", "slug": "radius_change_of_authorization"},
    {"id": "18_09", "topic": "FlexAuth and the Access Session Manager", "slug": "flexauth_and_the_access_session_manager"},
    {"id": "18_10", "topic": "Cisco ISE Architecture and Personas", "slug": "cisco_ise_architecture_and_personas"},
    {"id": "18_11", "topic": "ISE Policy Sets and Authorization Profiles", "slug": "ise_policy_sets_and_authorization_profil"},
    {"id": "19_01", "topic": "Threat Landscape and Attack Categories", "slug": "threat_landscape_and_attack_categories"},
    {"id": "19_02", "topic": "Layer 2 Attacks and Their Mitigations", "slug": "layer_2_attacks_and_their_mitigations"},
    {"id": "19_03", "topic": "Firewall Types and NGFW Capabilities", "slug": "firewall_types_and_ngfw_capabilities"},
    {"id": "19_04", "topic": "IPS and Threat Detection", "slug": "ips_and_threat_detection"},
    {"id": "19_05", "topic": "Endpoint Security and EDR", "slug": "endpoint_security_and_edr"},
    {"id": "19_06", "topic": "Zero Trust Principles", "slug": "zero_trust_principles"},
    {"id": "19_07", "topic": "SASE Architecture", "slug": "sase_architecture"},
    {"id": "19_08", "topic": "MACsec Operation and Frame Format", "slug": "macsec_operation_and_frame_format"},
    {"id": "19_09", "topic": "MACsec Key Agreement and AES-GCM Encryption", "slug": "macsec_key_agreement_and_aesgcm_encrypti"},
    {"id": "19_10", "topic": "TrustSec Security Group Tags", "slug": "trustsec_security_group_tags"},
    {"id": "19_11", "topic": "SGT Propagation: Inline Tagging and SXP", "slug": "sgt_propagation_inline_tagging_and_sxp"},
    {"id": "19_12", "topic": "TrustSec Policy Enforcement", "slug": "trustsec_policy_enforcement"},
    {"id": "19_13", "topic": "REST API Security Considerations", "slug": "rest_api_security_considerations"},
    {"id": "20_01", "topic": "SD-Access Solution Overview and Value", "slug": "sdaccess_solution_overview_and_value"},
    {"id": "20_02", "topic": "Fabric Roles: Edge, Border and Control Plane Nodes", "slug": "fabric_roles_edge_border_and_control_pla"},
    {"id": "20_03", "topic": "LISP as the SD-Access Control Plane", "slug": "lisp_as_the_sdaccess_control_plane"},
    {"id": "20_04", "topic": "VXLAN as the SD-Access Data Plane", "slug": "vxlan_as_the_sdaccess_data_plane"},
    {"id": "20_05", "topic": "TrustSec as the SD-Access Policy Plane", "slug": "trustsec_as_the_sdaccess_policy_plane"},
    {"id": "20_06", "topic": "Underlay Design and LAN Automation", "slug": "underlay_design_and_lan_automation"},
    {"id": "20_07", "topic": "Virtual Networks and Macro-Segmentation", "slug": "virtual_networks_and_macrosegmentation"},
    {"id": "20_08", "topic": "SGT-Based Micro-Segmentation Inside the Fabric", "slug": "sgtbased_microsegmentation_inside_the_fa"},
    {"id": "20_09", "topic": "Wireless Integration in SD-Access", "slug": "wireless_integration_in_sdaccess"},
    {"id": "20_10", "topic": "Interoperating with a Traditional Campus", "slug": "interoperating_with_a_traditional_campus"},
    {"id": "20_11", "topic": "Catalyst Center Architecture", "slug": "catalyst_center_architecture"},
    {"id": "20_12", "topic": "Catalyst Center Assurance and Analytics", "slug": "catalyst_center_assurance_and_analytics"},
    {"id": "20_13", "topic": "Catalyst Center Workflows and Provisioning", "slug": "catalyst_center_workflows_and_provisioni"},
    {"id": "21_01", "topic": "SD-WAN Solution Overview and Benefits", "slug": "sdwan_solution_overview_and_benefits"},
    {"id": "21_02", "topic": "The Four Planes of Cisco SD-WAN", "slug": "the_four_planes_of_cisco_sdwan"},
    {"id": "21_03", "topic": "vBond and the Orchestration Plane", "slug": "vbond_and_the_orchestration_plane"},
    {"id": "21_04", "topic": "vSmart and the Control Plane", "slug": "vsmart_and_the_control_plane"},
    {"id": "21_05", "topic": "vManage and the Management Plane", "slug": "vmanage_and_the_management_plane"},
    {"id": "21_06", "topic": "WAN Edge Routers and the Data Plane", "slug": "wan_edge_routers_and_the_data_plane"},
    {"id": "21_07", "topic": "OMP Route Advertisement", "slug": "omp_route_advertisement"},
    {"id": "21_08", "topic": "TLOC Structure and Colors", "slug": "tloc_structure_and_colors"},
    {"id": "21_09", "topic": "Zero-Touch Provisioning", "slug": "zerotouch_provisioning"},
    {"id": "21_10", "topic": "NAT Traversal and DTLS Tunnel Establishment", "slug": "nat_traversal_and_dtls_tunnel_establishm"},
    {"id": "21_11", "topic": "SD-WAN Control Policies", "slug": "sdwan_control_policies"},
    {"id": "21_12", "topic": "SD-WAN Data Policies", "slug": "sdwan_data_policies"},
    {"id": "21_13", "topic": "Application-Aware Routing", "slug": "applicationaware_routing"},
    {"id": "21_14", "topic": "SD-WAN Design Limitations and Considerations", "slug": "sdwan_design_limitations_and_considerati"},
    {"id": "22_01", "topic": "Python Data Types for Network Automation", "slug": "python_data_types_for_network_automation"},
    {"id": "22_02", "topic": "Python Control Flow and Functions", "slug": "python_control_flow_and_functions"},
    {"id": "22_03", "topic": "JSON Structure and Parsing", "slug": "json_structure_and_parsing"},
    {"id": "22_04", "topic": "XML and YAML Compared to JSON", "slug": "xml_and_yaml_compared_to_json"},
    {"id": "22_05", "topic": "YANG Data Models and Module Structure", "slug": "yang_data_models_and_module_structure"},
    {"id": "22_06", "topic": "NETCONF Operations and Datastores", "slug": "netconf_operations_and_datastores"},
    {"id": "22_07", "topic": "RESTCONF and Its HTTP Mapping", "slug": "restconf_and_its_http_mapping"},
    {"id": "22_08", "topic": "REST API Methods and Idempotency", "slug": "rest_api_methods_and_idempotency"},
    {"id": "22_09", "topic": "HTTP Response Codes and Error Handling", "slug": "http_response_codes_and_error_handling"},
    {"id": "22_10", "topic": "API Authentication: Basic, Token and Session", "slug": "api_authentication_basic_token_and_sessi"},
    {"id": "22_11", "topic": "Catalyst Center API Structure", "slug": "catalyst_center_api_structure"},
    {"id": "22_12", "topic": "SD-WAN Manager API Structure", "slug": "sdwan_manager_api_structure"},
    {"id": "22_13", "topic": "Ansible for Network Configuration", "slug": "ansible_for_network_configuration"},
    {"id": "22_14", "topic": "Puppet, Chef and Agent-Based Tools", "slug": "puppet_chef_and_agentbased_tools"},
    {"id": "22_15", "topic": "CI/CD Concepts for Network Configuration", "slug": "cicd_concepts_for_network_configuration"},
]
